/**
 * Maison Mercantile design reminder: retain the editorial product composition, but communicate B2B scope in three seconds.
 * Fragrance, Skincare and Makeup must have equal visual weight; supplied product imagery stays transparent about its status.
 */
import { Link } from "wouter";
import { ArrowRight, Check, Factory, FlaskConical, PackageCheck, ShieldCheck, Sparkles } from "lucide-react";
import { SiteShell, InquiryDrawer } from "@/components/SiteShell";
import { ProductCard } from "@/components/ProductCard";
import { products, type ProductCategory } from "@/data/products";

const categoryEntries: { category: ProductCategory; title: string; intro: string; href: string }[] = [
  { category: "fragrance", title: "Fragrance", intro: "Mists, scent profiles and private-label packaging.", href: "/collections/fragrance" },
  { category: "skincare", title: "Skincare", intro: "Care formats, routine products and custom development.", href: "/collections/skincare" },
  { category: "makeup", title: "Makeup", intro: "Colour formats, shade stories and branded components.", href: "/collections/makeup" },
];
const categoryProducts = categoryEntries.map((entry) => ({ ...entry, product: products.find((product) => product.category === entry.category)! }));

export default function Home() {
  return <SiteShell>
    <section className="hero-section hero-refined"><img className="hero-paper" src="/manus-storage/topperfume-hero-paper-still-life_92fd6502.jpg" alt="" /><div className="hero-copy"><p className="eyebrow">BEAUTY B2B PARTNER / PRIVATE LABEL · OEM · ODM</p><h1>Beauty products<br /><em>built for your brand.</em></h1><p className="hero-intro">We help beauty brands develop and manufacture <strong>Fragrance, Skincare and Makeup</strong>—from product concept and packaging to samples and production planning.</p><div className="hero-b2b-line"><span>PRIVATE LABEL</span><span>OEM</span><span>ODM</span></div><div className="hero-actions"><Link href="#products" className="text-link">Browse Products <ArrowRight size={16} /></Link><InquiryDrawer triggerLabel="Start Your Project" /></div><div className="hero-index"><span>01</span><span>Product-led development for beauty brands.</span></div></div><div className="hero-product-stage"><div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" /><img className="hero-product" src="/manus-storage/fragrance-jam-spill_f3448635.jpg" alt="Jam Spill fragrance mist" /><div className="hero-caption"><span>SUPPLIED PRODUCT VISUAL</span><strong>Jam Spill</strong><span>FRAGRANCE · 250 ML MIST</span></div><div className="hero-category-switch"><span>Fragrance</span><span>Skincare</span><span>Makeup</span></div></div></section>

    <section className="business-statement"><div className="section-index">01 / WHAT WE DO</div><h2>Develop the product.<br />Build the brand experience.</h2><div className="manifesto-body"><p>Start with a product reference, select your level of customization, then move to sample, quotation and project planning. The experience is deliberately designed for international beauty buyers—not for price-first browsing.</p><Link href="#products" className="circle-arrow"><ArrowRight size={24} /></Link></div></section>

    <section id="products" className="category-rail category-rail-refined"><div className="rail-heading"><div><p className="eyebrow">BROWSE BY CATEGORY</p><h2>Three equal ways to start.</h2></div><p className="category-rail-note">Each category opens to a fast product grid with sample and quotation paths.</p></div><div className="category-grid">{categoryProducts.map(({ category, title, intro, href, product }, index) => <Link href={href} className={`category-panel category-panel-refined ${category}-panel`} key={category}><img src={product.image} className="category-visual" alt={`${title} product visual`} /><div className="category-panel-body"><span>0{index + 1} / {title}</span><h3>{title}</h3><p>{intro}</p><small>{product.realImage ? "Supplied product visual" : "Concept visual — real photo needed"}</small></div><ArrowRight size={18} /></Link>)}</div></section>

    <section className="featured-section balanced-products"><div className="section-head"><div><p className="eyebrow">PRODUCTS AT A GLANCE</p><h2>One product from every category.</h2></div><Link href="/collections/fragrance" className="text-link">View all products <ArrowRight size={16} /></Link></div><div className="product-grid balanced-grid">{categoryProducts.map(({ product }, index) => <ProductCard product={product} index={index} key={product.slug} />)}</div></section>

    <section id="capabilities" className="capabilities-section"><div className="capabilities-image"><img src="/manus-storage/topperfume-packaging-study_f7ac65c2.jpg" alt="Unbranded beauty packaging development materials" /></div><div className="capabilities-copy"><p className="eyebrow">CUSTOM DEVELOPMENT, NOT A GENERIC CATALOGUE</p><h2>The work behind a product that feels yours.</h2><div className="capability-list"><p><Check size={17} /> Product development &amp; product selection</p><p><Check size={17} /> Formula, fragrance &amp; shade customization</p><p><Check size={17} /> Packaging, artwork &amp; logo customization</p><p><Check size={17} /> Sample requests, quotations &amp; project planning</p></div><InquiryDrawer triggerLabel="Start Your Project" /></div></section>

    <section className="trust-section"><div className="trust-heading"><p className="eyebrow">BUYER TRUST LAYER</p><h2>What buyers need<br />to evaluate next.</h2><p>We will replace every confirmation marker below with approved factory and certification evidence before the production website goes live.</p></div><div className="trust-grid"><article><FlaskConical size={18} /><h3>Product Development</h3><p>Product scope and development workflow [TO CONFIRM]</p></article><article><PackageCheck size={18} /><h3>Packaging</h3><p>Component, artwork and logo scope [TO CONFIRM]</p></article><article><ShieldCheck size={18} /><h3>Quality Control</h3><p>Quality process and documentation [TO CONFIRM]</p></article><article><Sparkles size={18} /><h3>Sample Development</h3><p>Sample process and timelines [TO CONFIRM]</p></article><article><Factory size={18} /><h3>Factory Capability</h3><p>Facility, capacity and market coverage [TO CONFIRM]</p></article><article><Check size={18} /><h3>Certifications</h3><p>Verified certificates and claims [TO CONFIRM]</p></article></div></section>

    <section className="process-section"><div><p className="eyebrow">A CLEAR BUYER PATH</p><h2>Browse products.<br />Make decisions.</h2></div><div className="process-grid"><article><span>01</span><h3>Browse</h3><p>Choose a category and compare product formats with the key B2B fields in view.</p></article><article><span>02</span><h3>Request</h3><p>Request a sample or quote from the specific product you are considering.</p></article><article><span>03</span><h3>Develop</h3><p>Confirm customization, MOQ and lead time with the right project context.</p></article></div></section>
    <section className="closing-banner"><Sparkles size={20} /><p>Choose a product, then move to sample, quote or customization.</p><InquiryDrawer triggerLabel="Start Your Project" /></section>
  </SiteShell>;
}
