import { SiteShell } from '@/components/SiteShell';
import { Seo } from '@/components/Seo';
import { privacySeo } from '@shared/seo';
import { OPEN_CONSENT } from '@/lib/consent';

export default function Privacy() {
  return <SiteShell><Seo page={privacySeo} /><article className="contact-page privacy-page"><p className="eyebrow">PRIVACY</p><h1>Privacy &amp; cookies</h1><p>Updated 14 September 2026</p>
    <h2>Who handles your inquiry</h2><p>TopPerfume is operated by Guiqi Technology Co., Ltd. Our public contact location is Baiyun District, Guangzhou, Guangdong, China. Contact <a href="mailto:melody888666@yeah.net">melody888666@yeah.net</a> or WhatsApp +86 190 6678 2710.</p>
    <h2>Information and purposes</h2><p>We receive the name, country or market, email and quantity you enter, together with any optional WhatsApp number, requirements and notes. An inquiry may also contain the selected product, size, unit price and product subtotal. We use these details to respond, prepare quotations and discuss order arrangements. Please do not include passwords or payment credentials.</p><p>Submitting an inquiry does not create an order and does not subscribe you to marketing. New-product and promotional email subscriptions are currently unavailable.</p>
    <h2>Processing and access</h2><p>Within our business, only the website owner reviews and handles customer inquiries. We use Vercel for hosting and technical processing, Resend for inquiry email transmission and our sales mailbox for receipt. These services may process technical request and delivery logs. Pages request fonts from Google Fonts. Choosing WhatsApp opens that service. Service providers may process information in countries other than yours; their services have their own privacy terms.</p>
    <h2>How long we keep information</h2><p>For inquiries that do not become orders, our retention rule is 12 months from the last substantive business contact. Records reaching that point are reviewed by the owner for deletion; any continued retention must have a documented business or legal reason. For completed transactions, we keep information as necessary to fulfil the order, maintain accounting records, meet applicable obligations and resolve disputes. The period depends on the record and the relevant requirements. You can contact us for information about your records.</p>
    <h2>Optional analytics and cookies</h2><p>Google Analytics 4 loads only after you allow analytics. It helps us understand visits, product views, contact-button clicks and inquiry submissions accepted by our delivery service. These events do not establish a qualified business inquiry. We do not use this setting to enable advertising personalization. Rejecting analytics leaves the catalogue and inquiry service available.</p><p>Your choice is stored in this browser's local storage until you change it or clear site data. If you agree, Google Analytics uses first-party analytics cookies. You can withdraw consent below; this stops future analytics and clears our accessible Google Analytics cookies. Withdrawal does not automatically delete data already collected.</p><button className="button-secondary" onClick={() => window.dispatchEvent(new Event(OPEN_CONSENT))}>Cookie preferences</button>
    <h2>Access, correction and deletion requests</h2><p>Email melody888666@yeah.net with the inquiry concerned and your request to access, correct or delete your information. The website owner reviews and handles requests each week and will communicate with you. We may need to verify your identity and consider recordkeeping obligations before completing a request.</p>
  </article></SiteShell>;
}
