/**
 * Maison Mercantile design reminder: a Product Detail page is a buyer decision surface.
 * The product visual remains dominant; visible specifications, confirmed order terms and direct commercial actions make the next step clear.
 */
import { Link, useParams } from "wouter";
import { ArrowLeft, ArrowRight, Check } from "lucide-react";
import { SiteShell, WhatsAppAction, WhatsAppCta } from "@/components/SiteShell";
import { customerValue, getDevelopmentScope, getProductCommercialType, getProductCustomTerms, getProductDecisionRows, getProductInquiryCustomizationNote, getProductStandardTerms } from "@/data/business";
import { getProduct, products } from "@/data/products";
import { ProductCard } from "@/components/ProductCard";

export default function ProductDetail() {
  const { slug } = useParams<{ slug: string }>();
  const product = getProduct(slug);
  if (!product) return <SiteShell><section className="not-found-page"><p className="eyebrow">PRODUCT NOT FOUND</p><h1>Let’s return to the collection.</h1><Link className="text-link" href="/collections/fragrance">Browse products <ArrowRight size={16} /></Link></section></SiteShell>;

  const related = products.filter((item) => item.category === product.category && item.slug !== product.slug).slice(0, 3);
  const context = { productName: product.name, sku: product.sku, productUrl: `/products/${product.slug}`, category: product.category, standardMoq: product.standardMoq, leadTime: product.leadTime, sampleAvailability: product.sampleAvailability, customizationNote: getProductInquiryCustomizationNote(product) };
  const decisionRows = getProductDecisionRows(product);
  const standardTerms = getProductStandardTerms(product);
  const customTerms = getProductCustomTerms(product);
  const customDisclaimer = getProductInquiryCustomizationNote(product);
  const detailValue = (value: string) => customerValue(value);
  const commercialType = getProductCommercialType(product);

  return <SiteShell>
    <section className="breadcrumb"><Link href={`/collections/${product.category}`}><ArrowLeft size={15} /> Back to {product.category}</Link><span>/</span><span>{product.name}</span></section>
    <section className={`pdp-hero pdp-${product.category}`}>
      <div className={`pdp-image-stage pdp-product-${product.slug}`}><span className="pdp-index">01 / {product.dataStatus === "confirmed" ? "PRODUCT" : "PRODUCT REFERENCE"}</span><img src={product.image} alt={`${product.name} product visual`} /><span className="pdp-visual-tag">{product.dataStatus === "confirmed" ? "Catalogue plate / product visual" : "Product visual / reference plate"}</span></div>
      <div className="pdp-copy">
        <p className="eyebrow">{product.category} / {product.productType || product.concentration || "product format"}</p><h1>{product.name}</h1>{product.nameStatus && <span className="product-name-status">{product.nameStatus}</span>}
        <p className="pdp-descriptor">{product.descriptor}</p><div className="pdp-tags">{product.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>
        {product.dataStatus === "confirmed" && <dl className="pdp-commercial-facts">
          {product.sku && <div><dt>SKU</dt><dd>{product.sku}</dd></div>}{product.productType && <div><dt>Product Type</dt><dd>{product.productType}</dd></div>}{product.gender && <div><dt>Suitable For</dt><dd>{product.gender}</dd></div>}{product.concentration && <div><dt>Concentration</dt><dd>{product.concentration}</dd></div>}{product.fragranceFamily && <div><dt>Fragrance Family</dt><dd>{product.fragranceFamily}</dd></div>}{product.primaryBenefit && <div><dt>Primary Benefit</dt><dd>{product.primaryBenefit}</dd></div>}{product.moisturePositioning && <div><dt>Moisture Positioning</dt><dd>{product.moisturePositioning}</dd></div>}{product.keyIngredients && <div><dt>Key Ingredients</dt><dd>{product.keyIngredients}</dd></div>}{product.texture && <div><dt>Texture</dt><dd>{detailValue(product.texture)}</dd></div>}{product.skinType && <div><dt>Skin Type</dt><dd>{detailValue(product.skinType)}</dd></div>}{product.fragrance && <div><dt>Fragrance</dt><dd>{detailValue(product.fragrance)}</dd></div>}{product.spf && <div><dt>SPF</dt><dd>{detailValue(product.spf)}</dd></div>}{product.visibleNotes && <div><dt>Visible Notes</dt><dd>{detailValue(product.visibleNotes)}</dd></div>}{product.remainingNotes && <div><dt>Remaining Notes</dt><dd>{detailValue(product.remainingNotes)}</dd></div>}{product.keyNotes && <div><dt>Key Notes</dt><dd>{detailValue(product.keyNotes)}</dd></div>}{product.edition && <div><dt>Edition</dt><dd>{detailValue(product.edition)}</dd></div>}{product.releaseYear && <div><dt>Release Year</dt><dd>{product.releaseYear}</dd></div>}{product.standardMoq && <div><dt>MOQ</dt><dd>{detailValue(product.standardMoq)}</dd></div>}{product.leadTime && <div><dt>Lead Time</dt><dd>{detailValue(product.leadTime)}</dd></div>}{product.b2bPrice && <div><dt>Suggested B2B Price</dt><dd>{detailValue(product.b2bPrice)}</dd></div>}
          {product.dermatologistTested && <div><dt>Dermatologist Tested</dt><dd>{product.dermatologistTested}</dd></div>}
        </dl>}
        {product.category === "makeup" && product.dataStatus === "confirmed" && <dl className="pdp-commercial-facts pdp-makeup-facts"><div><dt>Net Weight / Volume</dt><dd>{detailValue(product.format)}</dd></div>{product.setComponents && <div><dt>Set Includes</dt><dd>{detailValue(product.setComponents)}</dd></div>}{product.browDefinerSpec && <div><dt>Brow Definer</dt><dd>{detailValue(product.browDefinerSpec)}</dd></div>}{product.precisionBrowPencilSpec && <div><dt>Precision Brow Pencil</dt><dd>{detailValue(product.precisionBrowPencilSpec)}</dd></div>}{product.clearBrowGelSpec && <div><dt>Clear Brow Gel</dt><dd>{detailValue(product.clearBrowGelSpec)}</dd></div>}{product.numberOfShades && <div><dt>Number of Shades</dt><dd>{detailValue(product.numberOfShades)}</dd></div>}{product.colorFamily && <div><dt>Color Family</dt><dd>{detailValue(product.colorFamily)}</dd></div>}{product.paletteFormat && <div><dt>Palette Format</dt><dd>{detailValue(product.paletteFormat)}</dd></div>}{product.individualPanWeight && <div><dt>Individual Pan Weight</dt><dd>{detailValue(product.individualPanWeight)}</dd></div>}{product.finish && <div><dt>Finish</dt><dd>{detailValue(product.finish)}</dd></div>}{product.coverage && <div><dt>Coverage</dt><dd>{detailValue(product.coverage)}</dd></div>}{product.texture && <div><dt>Texture</dt><dd>{detailValue(product.texture)}</dd></div>}{product.vegan && <div><dt>Vegan</dt><dd>{detailValue(product.vegan)}</dd></div>}{product.veganCertification && <div><dt>Vegan Certification</dt><dd>{detailValue(product.veganCertification)}</dd></div>}{product.shadeOptions && <div><dt>Visible Shade / Finish Mix</dt><dd>{detailValue(product.shadeOptions)}</dd></div>}{product.shadeCodes && <div><dt>Shade Codes</dt><dd>{detailValue(product.shadeCodes)}</dd></div>}{product.ingredients && <div><dt>Ingredients</dt><dd>{detailValue(product.ingredients)}</dd></div>}</dl>}
        {product.category !== "makeup" && product.dataStatus === "confirmed" && product.setComponents && <dl className="pdp-commercial-facts pdp-set-facts"><div><dt>Set Includes</dt><dd>{detailValue(product.setComponents)}</dd></div>{product.ingredients && <div><dt>Ingredients</dt><dd>{detailValue(product.ingredients)}</dd></div>}</dl>}
        <div className="pdp-cta-row"><WhatsAppCta label="Request Free Sample" intent="sample" context={context} /><WhatsAppCta label="Get Wholesale Quote" intent="quote" context={context} className="button-rose" /><WhatsAppCta label="Customize / Private Label" intent="project" context={context} /><WhatsAppAction context={context} /></div><p className="pdp-disclaimer">Product context is attached. MOQ: {standardTerms[0].value}; {standardTerms[1].value}; Free Samples: {standardTerms[2].value}. Commercial type: {commercialType}. {customDisclaimer}</p><p className="pdp-intro pdp-story">{product.briefing}</p>
      </div>
    </section>
    <section className="decision-module"><div className="decision-module-copy"><p className="eyebrow">B2B DECISION MODULE</p><h2>Product details buyers need.</h2><p>SKU-level commercial terms are visible below. Contact us for details where product-specific scope has not yet been confirmed.</p></div><dl className="decision-grid">{decisionRows.map(({ label, value }) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
    <section className="order-pathways"><div className="order-pathways-intro"><p className="eyebrow">ORDER PATHWAYS</p><h2>Start standard.<br />Develop when ready.</h2><p>Choose the path that fits your buying stage. The product reference, quote and contact route remain attached either way.</p></div><div className="order-path-grid"><article className="order-path-card standard-order"><div className="order-path-title"><span>01</span><div><p>STANDARD ORDER</p><h3>For immediate product reference.</h3></div></div><dl>{standardTerms.map((term) => <div key={term.label}><dt>{term.label}</dt><dd>{term.value}</dd></div>)}</dl><WhatsAppCta label="Request Free Sample" intent="sample" context={context} /></article><article className="order-path-card custom-order"><div className="order-path-title"><span>02</span><div><p>CUSTOM ORDER</p><h3>For your branded brief.</h3></div></div><dl>{customTerms.map((term) => <div key={term.label}><dt>{term.label}</dt><dd>{term.value}</dd></div>)}</dl><WhatsAppCta label="Customize / Private Label" intent="project" context={context} className="button-rose" /></article></div></section>
    {product.notes && <section className="note-architecture"><div><p className="eyebrow">SCENT ARCHITECTURE</p><h2>A fragrance reference.</h2><p>Use this profile as a clear starting point for fragrance adaptation and brand positioning.</p></div><div className="note-grid"><article><span>TOP NOTES</span><p>{product.notes.top}</p></article><article><span>HEART NOTES</span><p>{product.notes.heart}</p></article><article><span>BASE NOTES</span><p>{product.notes.base}</p></article></div></section>}
    <section className="development-board"><div className="development-board-copy"><p className="eyebrow">COMMERCIAL PATHWAY</p><h2>{commercialType === "Branded Wholesale" ? "Wholesale terms, clearly routed." : "Develop when the brief is ready."}</h2><p>{commercialType === "Branded Wholesale" ? "This finished product is presented through a branded wholesale pathway. Contact us for product-specific wholesale options." : "Move into the appropriate Private Label, OEM or ODM conversation. Contact us for product-specific scope before committing to a custom order."}</p></div><div className="development-list"><p><Check size={19} /><span><strong>Commercial type</strong>{commercialType}</span></p><p><Check size={19} /><span><strong>Product expression</strong>{getDevelopmentScope(product.category)} Contact us for details.</span></p><p><Check size={19} /><span><strong>Packaging &amp; logo</strong>{getProductInquiryCustomizationNote(product)}</span></p><p><Check size={19} /><span><strong>Sample to quote</strong>Free samples are available; use the actions above with this exact product name, URL and category already attached.</span></p></div></section>
    <section className="related-section"><div className="section-head"><div><p className="eyebrow">RELATED PRODUCTS</p><h2>Keep browsing.</h2></div><Link className="text-link" href={`/collections/${product.category}`}>See all {product.category} <ArrowRight size={16} /></Link></div><div className="product-grid related-grid">{related.map((item, index) => <ProductCard product={item} index={index} key={item.slug} />)}</div></section>
    <section className="closing-banner"><Check size={20} /><p>Choose the next action: sample, quote or project.</p><WhatsAppCta label="Customize / Private Label" intent="project" context={context} /></section>
  </SiteShell>;
}
